### ISSUE TITLE
Background color for empty editor space is not set correctly

### ISSUE THREAD

**Issue by r0ckarong** [csutter/chester-atom-syntax#17]
I'm using Atom 1.18.0 with the Pristine theme (doesn't matter which theme it happens in any).

Using the chester syntax theme the background of the editor is in a lighter shade of grey/blue than the rest of the filled editor area. I can't find the property that handles this.

The scrollbar also will have the correct background color behind the bar itself but a lighter color in the scroll area, when you move the bar the color gets adjusted.

![screen shot 2017-08-08 at 14 38 59](https://user-images.githubusercontent.com/4920542/29073083-90e4600c-7c4a-11e7-8478-199e2720b016.png)
![screen shot 2017-08-08 at 14 39 09](https://user-images.githubusercontent.com/4920542/29073085-90eb836e-7c4a-11e7-91c5-df2332b74f53.png)
![screen shot 2017-08-08 at 14 39 15](https://user-images.githubusercontent.com/4920542/29073086-90f45444-7c4a-11e7-9ea1-ebe67c72af35.png)
![screen shot 2017-08-08 at 14 39 22](https://user-images.githubusercontent.com/4920542/29073084-90e7c4b8-7c4a-11e7-99d5-ae8cfeabeaf9.png)

**Comment by probablykasper** [comment]
This is not occurring for me, neither when I tried the Pristine UI theme. If you inspect the code, there should be divs that contain 6 lines each, those containers have a background-color and should have full width, like this;
![screen shot 2017-08-08 at 3 14 53 pm](https://user-images.githubusercontent.com/11315492/29073552-5afea766-7c4c-11e7-9ef4-ec4697376cf6.png)
It does not look like that's the case for you, and that it gets full width when you have your cursor inside, or select part of it. That's my guess, would be nice to see if that's the case.

What happens when you resize your window? Does the dark part stay as wide, or does it expand?

Does this only happen in Chester? Could it be interfering with another package? Please try turning other packages off to find out, or tell me which packages you have. I could see it being the one that gives you colored preview of your code (Forgot it's name)

**Comment by r0ckarong** [comment]
I've gone through all the packages and dis/enabled them one by one. No effect. Then I did some cleanup of packages that I never used in the first place but had installed at some point. After restart now I don't see this phenomenon anymore. Maybe some incompatibility. If it reappears I will do more throrough testing. For now I'm closing this. Sorry to have bothered you.

**Comment by probablykasper** [comment]
No problem, thank you for reporting :)
