### ISSUE TITLE
Some Design Syntax isn't Unifrom

### ISSUE THREAD

**Issue by ahmad2smile** [csutter/chester-atom-syntax#18]
variables in if block are acting differently than in else block.

![screenshot 21](https://user-images.githubusercontent.com/6108922/29248565-79ca781e-8034-11e7-83de-1e0ec3e16127.png)

**Comment by probablykasper** [comment]
I think you have a syntax error above this code, as the punctation is supposed to be white, not yellow. Care to check it out, and share a screenshot if that's not it?

**Comment by ahmad2smile** [comment]
Yes. I checked the source code now. It's design is ok now. I took the above prtScrn while I was working on this project. My apologies for not double checking before posting it as an issue.

New prtScrn:
![screenshot 22](https://user-images.githubusercontent.com/6108922/29248990-479e887a-803f-11e7-82c8-3a976009d145.png)

**Comment by probablykasper** [comment]
It still should not look like that. The parentheses and semicolons should all be white, at least if this is JavaScript.

**Comment by ahmad2smile** [comment]
This is typescript. While we are considering this.. I think chained variables should look different at each switch... like this keyword should be different color then .playPauseButton should be different... then .style should be different.. and so on n so on... 

Just what I think...

**Comment by probablykasper** [comment]
@ahmad2smile Not sure if there's anything I can do, all the package does is apply colors to classes. The "this" keyword only has the variable class. In an object "object.property.user.age", I could color the first, last and middle ones differently if I want to. That might not work at all for Typescript, since there does not seem to be a native language-typescript package.

Still though, any idea why the parentheses and semicolons are yellow?

**Comment by ahmad2smile** [comment]
I have no idea.. never worked on this.

**Comment by probablykasper** [comment]
@ahmad2smile Do cmd-shift-i, or ctrl-shift-i if you're on Windows (I hope). Use the icon all the way in the top-left to select a yellow semicolon, then tell me all the classes it has. I assume you're familiar with the inspector for websites, this is no different than that. The semicolon should be in a <span>, and the classes all start with `syntax--`.

**Comment by ahmad2smile** [comment]
All the classes it had

 syntax--punctuation syntax--terminator syntax--statement syntax--ts

**Comment by probablykasper** [comment]
@ahmad2smile Hmm, alright. Figured out how to make the punctuations white (assuming you use atom-typescript), question is do you think it's a good idea to have them white instead of yellow?

Everything inside of a class (I'm assuming your code is in a class) in TypeScript basically inherits syntax--class, but in JavaScript this is not the case so only the class name is yellow there.

**Comment by ahmad2smile** [comment]
No, I think function definition parenthesis should be different then when you call them. It helps in situations like this in promise then function:

![screenshot 24](https://user-images.githubusercontent.com/6108922/29262749-58ca3ca6-80ef-11e7-9024-ed1306a038e7.png)


But look at the minimap.. there is too much Red and Yellow... maybe there is something to consider.

**Comment by probablykasper** [comment]
@ahmad2smile The red is just variable colors, and as far as I know most syntax themes act that way - Doesn't look too pretty with objects, I know.

White is basically the default color stuff gets when nothing else is applied - That's the case with yellow here as they just inherit the yellow from the class. Though, I'm not sure if it's just because of classes, or if you're using that at all. Would be very helpful if you were willing to share the whole file

**Comment by ahmad2smile** [comment]
Sorry. It's a private repo for some client. I don't think I'm allowed to...

still it's a Typescript Class and all of these methods are in class.

**Comment by probablykasper** [comment]
@ahmad2smile Okay, no problem. I believe I'll just make everything inside classes white.

**Comment by probablykasper** [comment]
@ahmad2smile Do you think the white is looking good?
![screen shot 2017-08-14 at 10 50 29 am](https://user-images.githubusercontent.com/11315492/29269494-12242f0c-80f2-11e7-8d14-60dedd2c0be7.png)
![screen shot 2017-08-14 at 10 50 23 am](https://user-images.githubusercontent.com/11315492/29269498-15e0b976-80f2-11e7-8f07-0f1ad3e9916f.png)

**Comment by ahmad2smile** [comment]
maybe make the function definition color something different... too much white just feels as if there was no design for these things... and I think parenthesis in white are a good idea. they really standout ....

**Comment by ahmad2smile** [comment]
Can you please consider mixing some of the ideas from Monokia Syntex Theme... like italic input parameters and also the italic braces of function definition...

<img width="707" alt="68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3637313337382f323236353637312f64303265626565382d396538352d313165332d396238632d3132623263623730313565332e706e67" src="https://user-images.githubusercontent.com/6108922/29274448-5bac376c-8121-11e7-8a82-c9f287bd67d3.png">

**Comment by ahmad2smile** [comment]
I always gets stuck b/w choosing Monokai or your Theme...

**Comment by probablykasper** [comment]
@ahmad2smile The functions are supposed to be blue, like the one below, but I'm pretty certain "atom-typescript" is incorrectly adding the class "entity" instead of "syntax--entity" inside classes. Either way, fixed that.

I'm not really a fan of the italics in the Monokia theme, sorry.
